server:
  port: 8001
  error:
    include-stacktrace: never
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://18.220.225.117:30001/bc107-pocket-pay?useSSL=false&serverTimezone=UTC
    username: root
    password: Bootcamp@107!
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    table: user_service_flyway_schema_history
    mixed: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true