server:
  port: 8002
spring:
  application:
    name: transaction-service
  datasource:
    url:
      jdbc:mysql://18.220.225.117:30001/bc107-pocket-pay?useSSL=false&serverTimezone=UTC
    username:
        root
    password:
        Bootcamp@107!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
